### PR TITLE
Feature/130

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
- Update to @material-ui v4 
- Components working as expected
- Bring netpyne-geppetto repository to NetPyNE-UI
- Merge with File Upload / Download functionality for docker containers

Watch out
- Casper tests are broken for good
- Styling was not included
- Merging with development will trigger CF staging deployment

Next steps
- Bring redux branch to development after this branch is merge
- Test that all minor sync issues solved in redux branch are not broken

### CODE REVIEW

**Comment by rodriguez-facundo** [comment]
yeap, will do that!

**Comment by rodriguez-facundo** [comment]
Hi @filippomc 👋, this branch is deployed here http://34.68.113.100 with all the fixes we discussed on friday. It includes the redux stuff to remove geppetto triggers (a PR that was pending in netpyne-geppetto).

cc: @ddelpiano

**Comment by filippomc** [comment]
The demo looks much better, still problems with Travis I can see

**Comment by rodriguez-facundo** [comment]
Removed the casper test for travis.

**Pull request merged**
