### PR TITLE
#311 warn user before importing a model if model instantiated or simulated

### PR DESCRIPTION
**Pull request by Muhaddatha**
- Display warning dialog when user tries to import a model, but an old model is already instantiated or simulated.
- Current message: 
image

@enicolasgomez @ddelpiano What do you think about this message in the dialog?

### CODE REVIEW

**Comment by enicolasgomez** [comment]
@Muhaddatha some comments here:

- if I load Tutorial 1 and then try to import the action dialog continues executing as modelState is set not NOT_INSTANTIATED for some reason
- we should extend the funcitonality to other action types, not only importModel

**Comment by filippomc** [comment]
> @Muhaddatha some comments here:
> 
> * if I load Tutorial 1 and then try to import the action dialog continues executing as modelState is set not NOT_INSTANTIATED for some reason
> * we should extend the funcitonality to other action types, not only importModel

Instantiation happens after the instantiation/simulation is triggered, so it's fine I think that the state is still not instantiated after only loading the tutorial, is that maybe the case?

**Comment by Muhaddatha** [comment]
@filippomc that's right. When a tutorial is clicked, the redux state doesn't change.

**Comment by Muhaddatha** [comment]
Updated code: https://github.com/MetaCell/NetPyNE-UI/pull/454

**Pull request closed without merging**
