### PR TITLE
Fix issue with fast delete of field content

### PR DESCRIPTION
**Pull request by aranega**
When a field content is deleted too quickly (before the sync mechanism happens), an exception is raised in the Python side.
This behavior doesn't occur if you type a value in a field, wait a little bit that the sync happens, and delete it.
What's happening is that the code related to the netpyne field tries to delete a key that doesn't exists yet (see the video below).

https://github.com/MetaCell/NetPyNE-UI/assets/2317394/e0835f0d-450e-4358-89fa-bfcee75e3171

The fix removes this behavior (see video below)

https://github.com/MetaCell/NetPyNE-UI/assets/2317394/6ca38331-1975-4081-841a-e05019e1aaef

### CODE REVIEW

**Comment by ddelpiano** [comment]
all tests are failing here, @SimaoBolota-MetaCell @aranega could you sync to understand the problem please? Thx

**Comment by aranega** [comment]
@ddelpiano I think it's just a problem of sync with `development`, the original PR was done from the `development` branch where the `release/1.0.0` wasn't merged yet.

**Comment by aranega** [comment]
@ddelpiano After a small investivation, it looks like some ids in the CSS selectors for DOM elements are not found. In a general way, the CSS selectors are not up-to-date with `develop` for the tests, part of each test is tailored to run with the `master` version of the code at the moment. However, I'm not sure at which point the tests we have consider only `master` or `development` for the code, it's a little bit confusing.

**Comment by SimaoBolota-MetaCell** [comment]
Hi @ddelpiano @aranega 
Thanks for the investigation @aranega 
regarding the Save_Open Test, it is expected to fail due to this bug here https://metacell.atlassian.net/browse/NETPYNE-153 
Regarding the RxD-test I'm checking it out, it might be just a threshold or something

**Comment by SimaoBolota-MetaCell** [comment]
Fixed now! 
@aranega @ddelpiano

**Review by ddelpiano — APPROVED** [review]

**Comment by ddelpiano** [comment]
@enicolasgomez could you please review this and merge if you are ok? Thanks!

**Review by enicolasgomez — APPROVED** [review]

**Pull request merged**
