### PR TITLE
Feature/depandabot 20231030

### PR DESCRIPTION
**Pull request by enicolasgomez**

### CODE REVIEW

**Comment by SimaoBolota-MetaCell** [comment]
I am not sure what is happening. It errors out as soon as the tests start with the following error: `Cannot read property 'jest' of undefined` 

I tried the exact same steps taken by the github actions locally for this branch and I was able to run the tests with no problem (also with this branch deployed in dev - https://g.codefresh.io/build/656e202f715ff3ea041a04e1). The tests fail but that's because these are outdated compared to the one's in development.

Steps taken:

1. Clone repo
2. Checkout this branch feature/depandabot_20231030
3. cd tests/frontend/e2e
4. npm ci
5. npm run Tutorial_1_test (for example) - the tests start up with no jest undefined error while in github actions it immediately fails



@enicolasgomez @ddelpiano

**Comment by ddelpiano** [comment]
https://github.com/MetaCell/NetPyNE-UI/pull/746#issue-1802925563
@enicolasgomez can we move to pyneuroml > 1.0.9 as per comment from @sanjayankur31, please?

**Comment by ddelpiano** [comment]
@SimaoBolota-MetaCell I don't see anything obvious for jest to fail, 2 suggestions:
- remove the yarn lock since the dockerfile uses npm
- regenerate the package-lock json so that we can see if this works.

**Comment by SimaoBolota-MetaCell** [comment]
Did what you suggested @ddelpiano @enicolasgomez 

- removed the yarn.lock file
- regenerated package-lock.json

and am still getting the same error on the tests workflow from github actions
image

**Comment by SimaoBolota-MetaCell** [comment]
Now the build runs locally 
image
 and the tests pass on github actions as can be seen in the details
@enicolasgomez @ddelpiano

**Review by ddelpiano — APPROVED** [review]

**Pull request merged**
